# Permalinks
permalink:           pretty

# Setup
title:               Samantha Rood
tagline:             Beginning Of A Data Science Blog
url:                 http://samrood.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Samantha Rood
  #url:               https://twitter.com/zaglamir
  email:             samantharood2@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/samrood

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
